### PR TITLE
Mr departments get all

### PR DESCRIPTION
**Pull request by MattRowee**
Description
-User should be able to GET an index of all Department names, budgets and number of employees, by clicking the "DEPARTMENT" afjordance in the navbar.

##TESTING CRITERIA
git add and git commit what you're working on on your branch
git checkout master to switch to your local master branch
git fetch --all will give you access to your teammate's branches (if they've pushed them up)
git checkout mr-departmentsGetAll to access my branch.
If you don't see the most recent version of their files, try git pull origin mr-departmentsGetAll on your server on my branch and make sure everything looks okay.
Once server is running, use your navbar and click on the 'DEPARTMENTS' afjordance.
Revel in the beauty of the data you have requested being correctly displayed.

[ x] I have made corresponding changes to the documentation
[x ] My changes generate no new errors

image

### CODE REVIEW

**Comment by Downeastrussell** [comment]
Looks good. 🥇 ---Don't listen to me! Add proper description

**Comment by dalesaul** [comment]
agreed. good pr for Ticket 1---Actually please add a better description dude.

**Comment by ColonelSped** [comment]
👎 
Please provide proper description.

**Comment by ColonelSped** [comment]
👍

**Pull request merged**
